/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.html',
    './market-suggestions/*.html',
    './understand-content/*.html',
    './popup.js',
    './market-suggestions/*.js',
    './understand-content/*.js',
  ],
  // System-aware: DaisyUI applies `darkTheme` automatically via prefers-color-scheme
  darkMode: ['media'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Geist',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        mono: [
          'Geist Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Consolas',
          'monospace',
        ],
      },
      borderRadius: {
        xl: '14px',
        '2xl': '18px',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    logs: false,
    themes: [
      {
        light: {
          'color-scheme': 'light',
          primary: '#0d9488',
          'primary-content': '#ffffff',
          secondary: '#3f3f46',
          'secondary-content': '#ffffff',
          accent: '#0d9488',
          'accent-content': '#ffffff',
          neutral: '#18181b',
          'neutral-content': '#fafafa',
          'base-100': '#ffffff',
          'base-200': '#f4f4f5',
          'base-300': '#e4e4e7',
          'base-content': '#18181b',
          info: '#0ea5e9',
          success: '#0d9488',
          warning: '#d97706',
          error: '#dc2626',
          '--rounded-box': '14px',
          '--rounded-btn': '10px',
          '--rounded-badge': '8px',
          '--border-btn': '1px',
          '--animation-btn': '0.18s',
          '--tab-radius': '8px',
        },
      },
      {
        dark: {
          'color-scheme': 'dark',
          primary: '#2dd4bf',
          'primary-content': '#042f2a',
          secondary: '#a1a1aa',
          'secondary-content': '#18181b',
          accent: '#2dd4bf',
          'accent-content': '#042f2a',
          neutral: '#fafafa',
          'neutral-content': '#18181b',
          'base-100': '#0b0b0c',
          'base-200': '#151517',
          'base-300': '#26262a',
          'base-content': '#fafafa',
          info: '#38bdf8',
          success: '#2dd4bf',
          warning: '#f59e0b',
          error: '#f87171',
          '--rounded-box': '14px',
          '--rounded-btn': '10px',
          '--rounded-badge': '8px',
          '--border-btn': '1px',
          '--animation-btn': '0.18s',
          '--tab-radius': '8px',
        },
      },
    ],
    darkTheme: 'dark',
  },
};
